/wx250s:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      gripper_controller:
        type: joint_trajectory_controller/JointTrajectoryController
  arm_controller:
    ros__parameters:
      joints:
        - waist
        - shoulder
        - elbow
        - forearm_roll
        - wrist_angle
        - wrist_rotate
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 50.0
      action_monitor_rate: 50.0
      allow_nonzero_velocity_at_trajectory_end: true
      constraints:
        stopped_velocity_tolerance: 0.02
        goal_time: 0.5
  gripper_controller:
    ros__parameters:
      joints:
        - left_finger
      interface_name: position
      command_interfaces:
        - position
      state_interfaces:
        - position
      allow_nonzero_velocity_at_trajectory_end: true
  joint_state_broadcaster:
    ros__parameters:
      joints:
        - waist
        - shoulder
        - elbow
        - forearm_roll
        - wrist_angle
        - wrist_rotate
        - gripper
        - left_finger
